# Generated by Django 5.2.17 on 2026-09-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shape', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('kind', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('role', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('short', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(blank=True, max_length=40)),
                ('confidence', models.CharField(blank=True, max_length=1)),
                ('rank', models.PositiveSmallIntegerField(default=3)),
                ('period', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('geometry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.geometry')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('dx', models.FloatField(default=0)),
                ('dy', models.FloatField(default=0)),
                ('spec', models.JSONField(default=dict)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.feature')),
            ],
        ),
        migrations.CreateModel(
            name='MapView',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=300)),
                ('scale', models.PositiveIntegerField()),
                ('bounds', models.JSONField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('scale__gt', 0)), name='positive_map_scale')],
            },
        ),
        migrations.CreateModel(
            name='MapState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.revision')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('paragraph', models.PositiveIntegerField(blank=True, null=True)),
                ('reference', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.feature')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atlas.source')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('z', models.PositiveIntegerField()),
                ('recipe', models.JSONField(default=dict)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.feature')),
                ('geometry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atlas.geometry')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atlas.style')),
            ],
            options={
                'ordering': ['z', 'key'],
            },
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1), ('rank__lte', 3)), name='feature_rank_1_3'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__in', ['', 'A', 'B', 'C', 'U'])), name='feature_confidence'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence', 'U'), ('geometry__isnull', True), ('object_type', 'unplaced')), models.Q(models.Q(('object_type', 'unplaced'), _negated=True), ('geometry__isnull', False)), _connector='OR'), name='feature_geometry_presence'),
        ),
        migrations.AddConstraint(
            model_name='mapstate',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='singleton_map_state'),
        ),
    ]
