# Generated by Django 5.2.17 on 2026-09-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_map_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
