# Generated by Django 5.2.17 on 2026-09-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_alter_feature_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('ext', models.CharField(max_length=8)),
                ('original_name', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feature_key', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('characters', models.ManyToManyField(blank=True, to='atlas.character')),
                ('tags', models.ManyToManyField(blank=True, to='atlas.tag')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__isnull', True), models.Q(('year__gte', 1850), ('year__lte', 2100)), _connector='OR'), name='photo_year_range')],
            },
        ),
    ]
