# Generated by Django 5.2.17 on 2026-09-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_photogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='paragraph',
        ),
    ]
