# Generated by Django 5.2.17 on 2026-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_remove_evidence_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption_ru',
            field=models.TextField(blank=True, default=''),
        ),
    ]
