# Generated by Django 5.2.17 on 2026-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_photo_caption_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('ext', models.CharField(max_length=8)),
                ('original_name', models.CharField(max_length=255)),
                ('feature_key', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('alt', models.TextField()),
                ('alt_ru', models.TextField(blank=True, default='')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['feature_key', 'year'],
                'constraints': [models.UniqueConstraint(fields=('feature_key', 'year'), name='cover_unique_feature_year'), models.CheckConstraint(condition=models.Q(('year__gte', 1850), ('year__lte', 2100)), name='cover_year_range'), models.CheckConstraint(condition=models.Q(('feature_key', ''), _negated=True), name='cover_feature_required'), models.CheckConstraint(condition=models.Q(('alt', ''), _negated=True), name='cover_alt_required')],
            },
        ),
    ]
