# Generated by Django 5.2.17 on 2026-09-27

import hashlib
import json
from django.db import migrations, models


FIELDS = ('about', 'confidence_explanation')


def _canonical(value):
    if isinstance(value, dict):
        result = {key: _canonical(item) for key, item in value.items()}
        if set(result) == {'format', 'tables'}:
            for rows in result['tables'].values():
                rows.sort(key=lambda row: row['key'])
        return result
    if isinstance(value, list):
        return [_canonical(item) for item in value]
    if isinstance(value, float) and value.is_integer():
        return int(value)
    return value


def _digest(document):
    payload = json.dumps(_canonical(document), ensure_ascii=False, sort_keys=True,
                         separators=(',', ':'), allow_nan=False)
    return hashlib.sha256(payload.encode()).hexdigest()


def update_revision_snapshots(apps, schema_editor):
    Revision = apps.get_model('atlas', 'Revision')
    for revision in Revision.objects.iterator():
        changed = False
        for document in (revision.before, revision.after):
            for feature in document.get('tables', {}).get('feature', []):
                for field in FIELDS:
                    if field not in feature:
                        feature[field] = ''
                        changed = True
        if changed:
            revision.digest = _digest(revision.after)
            revision.save(update_fields=['before', 'after', 'digest'])


def revert_revision_snapshots(apps, schema_editor):
    Revision = apps.get_model('atlas', 'Revision')
    for revision in Revision.objects.iterator():
        changed = False
        for document in (revision.before, revision.after):
            for feature in document.get('tables', {}).get('feature', []):
                for field in FIELDS:
                    if field in feature:
                        feature.pop(field)
                        changed = True
        if changed:
            revision.digest = _digest(revision.after)
            revision.save(update_fields=['before', 'after', 'digest'])


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0007_placecover'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feature',
            name='confidence_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(update_revision_snapshots, revert_revision_snapshots),
    ]
