-- PostgreSQL 17 application schema; REVIEW ONLY, NOT an installation script.
-- Apply migrations with: python manage.py migrate --noinput
-- Run atlas seed separately after migrations. No novel text is required.
CREATE TABLE "atlas_setting" ("key" varchar(100) NOT NULL PRIMARY KEY, "value" jsonb NOT NULL);
CREATE TABLE "atlas_geometry" ("key" varchar(100) NOT NULL PRIMARY KEY, "shape" jsonb NOT NULL);
CREATE TABLE "atlas_style" ("key" varchar(100) NOT NULL PRIMARY KEY, "value" jsonb NOT NULL);
CREATE TABLE "atlas_source" ("key" varchar(100) NOT NULL PRIMARY KEY, "title" varchar(500) NOT NULL, "kind" varchar(20) NOT NULL, "url" varchar(2000) NOT NULL, "role" text NOT NULL, "metadata" jsonb NOT NULL);
CREATE TABLE "atlas_feature" ("key" varchar(100) NOT NULL PRIMARY KEY, "object_type" varchar(20) NOT NULL, "name" varchar(300) NOT NULL, "short" varchar(150) NOT NULL, "kind" varchar(40) NOT NULL, "confidence" varchar(1) NOT NULL, "rank" smallint NOT NULL CHECK ("rank" >= 0), "period" varchar(200) NOT NULL, "note" text NOT NULL, "geometry_id" varchar(100) NULL, "metadata" jsonb NOT NULL, CONSTRAINT "feature_rank_1_3" CHECK (("rank" >= 1 AND "rank" <= 3)), CONSTRAINT "feature_confidence" CHECK ("confidence" IN ('', 'A', 'B', 'C', 'U')), CONSTRAINT "feature_geometry_presence" CHECK ((("confidence" = 'U' AND "geometry_id" IS NULL AND "object_type" = 'unplaced') OR (NOT ("object_type" = 'unplaced') AND "geometry_id" IS NOT NULL))));
CREATE TABLE "atlas_component" ("key" varchar(100) NOT NULL PRIMARY KEY, "feature_id" varchar(100) NULL, "geometry_id" varchar(100) NULL, "style_id" varchar(100) NOT NULL, "z" integer NOT NULL CHECK ("z" >= 0), "recipe" jsonb NOT NULL);
CREATE TABLE "atlas_label" ("key" varchar(100) NOT NULL PRIMARY KEY, "feature_id" varchar(100) NULL, "text" varchar(300) NOT NULL, "dx" double precision NOT NULL, "dy" double precision NOT NULL, "spec" jsonb NOT NULL);
CREATE TABLE "atlas_evidence" ("key" varchar(100) NOT NULL PRIMARY KEY, "feature_id" varchar(100) NOT NULL, "source_id" varchar(100) NOT NULL, "paragraph" integer NULL CHECK ("paragraph" >= 0), "reference" text NOT NULL, "note" text NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0));
CREATE TABLE "atlas_mapview" ("key" varchar(100) NOT NULL PRIMARY KEY, "title" varchar(150) NOT NULL, "subtitle" varchar(300) NOT NULL, "scale" integer NOT NULL CHECK ("scale" >= 0), "bounds" jsonb NOT NULL, CONSTRAINT "positive_map_scale" CHECK ("scale" > 0));
CREATE TABLE "atlas_revision" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created" timestamp with time zone NOT NULL, "author" varchar(150) NOT NULL, "reason" text NOT NULL, "before" jsonb NOT NULL, "after" jsonb NOT NULL, "digest" varchar(64) NOT NULL);
CREATE TABLE "atlas_mapstate" ("id" smallint NOT NULL PRIMARY KEY CHECK ("id" >= 0), "initialized" boolean NOT NULL, "revision_id" bigint NULL, CONSTRAINT "singleton_map_state" CHECK ("id" = 1));
CREATE INDEX "atlas_setting_key_9139fbc5_like" ON "atlas_setting" ("key" varchar_pattern_ops);
CREATE INDEX "atlas_geometry_key_f2732343_like" ON "atlas_geometry" ("key" varchar_pattern_ops);
CREATE INDEX "atlas_style_key_f54fea1e_like" ON "atlas_style" ("key" varchar_pattern_ops);
CREATE INDEX "atlas_source_key_a91ec764_like" ON "atlas_source" ("key" varchar_pattern_ops);
ALTER TABLE "atlas_feature" ADD CONSTRAINT "atlas_feature_geometry_id_0a610ab6_fk_atlas_geometry_key" FOREIGN KEY ("geometry_id") REFERENCES "atlas_geometry" ("key") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "atlas_feature_key_a0b637dc_like" ON "atlas_feature" ("key" varchar_pattern_ops);
CREATE INDEX "atlas_feature_geometry_id_0a610ab6" ON "atlas_feature" ("geometry_id");
CREATE INDEX "atlas_feature_geometry_id_0a610ab6_like" ON "atlas_feature" ("geometry_id" varchar_pattern_ops);
ALTER TABLE "atlas_component" ADD CONSTRAINT "atlas_component_feature_id_3296043d_fk_atlas_feature_key" FOREIGN KEY ("feature_id") REFERENCES "atlas_feature" ("key") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "atlas_component" ADD CONSTRAINT "atlas_component_geometry_id_792da61d_fk_atlas_geometry_key" FOREIGN KEY ("geometry_id") REFERENCES "atlas_geometry" ("key") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "atlas_component" ADD CONSTRAINT "atlas_component_style_id_ac8b41f9_fk_atlas_style_key" FOREIGN KEY ("style_id") REFERENCES "atlas_style" ("key") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "atlas_component_key_95fc7b51_like" ON "atlas_component" ("key" varchar_pattern_ops);
CREATE INDEX "atlas_component_feature_id_3296043d" ON "atlas_component" ("feature_id");
CREATE INDEX "atlas_component_feature_id_3296043d_like" ON "atlas_component" ("feature_id" varchar_pattern_ops);
CREATE INDEX "atlas_component_geometry_id_792da61d" ON "atlas_component" ("geometry_id");
CREATE INDEX "atlas_component_geometry_id_792da61d_like" ON "atlas_component" ("geometry_id" varchar_pattern_ops);
CREATE INDEX "atlas_component_style_id_ac8b41f9" ON "atlas_component" ("style_id");
CREATE INDEX "atlas_component_style_id_ac8b41f9_like" ON "atlas_component" ("style_id" varchar_pattern_ops);
ALTER TABLE "atlas_label" ADD CONSTRAINT "atlas_label_feature_id_0da9c1fa_fk_atlas_feature_key" FOREIGN KEY ("feature_id") REFERENCES "atlas_feature" ("key") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "atlas_label_key_d9080107_like" ON "atlas_label" ("key" varchar_pattern_ops);
CREATE INDEX "atlas_label_feature_id_0da9c1fa" ON "atlas_label" ("feature_id");
CREATE INDEX "atlas_label_feature_id_0da9c1fa_like" ON "atlas_label" ("feature_id" varchar_pattern_ops);
ALTER TABLE "atlas_evidence" ADD CONSTRAINT "atlas_evidence_feature_id_53d0dc22_fk_atlas_feature_key" FOREIGN KEY ("feature_id") REFERENCES "atlas_feature" ("key") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "atlas_evidence" ADD CONSTRAINT "atlas_evidence_source_id_55ef9104_fk_atlas_source_key" FOREIGN KEY ("source_id") REFERENCES "atlas_source" ("key") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "atlas_evidence_key_7108ad3a_like" ON "atlas_evidence" ("key" varchar_pattern_ops);
CREATE INDEX "atlas_evidence_feature_id_53d0dc22" ON "atlas_evidence" ("feature_id");
CREATE INDEX "atlas_evidence_feature_id_53d0dc22_like" ON "atlas_evidence" ("feature_id" varchar_pattern_ops);
CREATE INDEX "atlas_evidence_source_id_55ef9104" ON "atlas_evidence" ("source_id");
CREATE INDEX "atlas_evidence_source_id_55ef9104_like" ON "atlas_evidence" ("source_id" varchar_pattern_ops);
CREATE INDEX "atlas_mapview_key_3d673c63_like" ON "atlas_mapview" ("key" varchar_pattern_ops);
ALTER TABLE "atlas_mapstate" ADD CONSTRAINT "atlas_mapstate_revision_id_3fbb9404_fk_atlas_revision_id" FOREIGN KEY ("revision_id") REFERENCES "atlas_revision" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "atlas_mapstate_revision_id_3fbb9404" ON "atlas_mapstate" ("revision_id");
-- Migration 0002 also inserts the singleton atlas_mapstate row (id=1).
